// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW9oD82xBVUsPmjCC38pUpNG0cuukkmwM',
    appId: '1:189308148705:web:53b96b152001e9999910a0',
    messagingSenderId: '189308148705',
    projectId: 'travel-journal-app-377b6',
    authDomain: 'travel-journal-app-377b6.firebaseapp.com',
    databaseURL: 'https://travel-journal-app-377b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-app-377b6.firebasestorage.app',
    measurementId: 'G-3SK217BJSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBop9d5Vk8DAskfAc06KecioTqnQXw_QZo',
    appId: '1:189308148705:android:9934494f6c4573bc9910a0',
    messagingSenderId: '189308148705',
    projectId: 'travel-journal-app-377b6',
    databaseURL: 'https://travel-journal-app-377b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-app-377b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL_klsxI2-g4m5BRHYjazfugy_RWmRL0s',
    appId: '1:189308148705:ios:667a22b44b6ed9719910a0',
    messagingSenderId: '189308148705',
    projectId: 'travel-journal-app-377b6',
    databaseURL: 'https://travel-journal-app-377b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-app-377b6.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL_klsxI2-g4m5BRHYjazfugy_RWmRL0s',
    appId: '1:189308148705:ios:667a22b44b6ed9719910a0',
    messagingSenderId: '189308148705',
    projectId: 'travel-journal-app-377b6',
    databaseURL: 'https://travel-journal-app-377b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-app-377b6.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW9oD82xBVUsPmjCC38pUpNG0cuukkmwM',
    appId: '1:189308148705:web:007ad6071da451739910a0',
    messagingSenderId: '189308148705',
    projectId: 'travel-journal-app-377b6',
    authDomain: 'travel-journal-app-377b6.firebaseapp.com',
    databaseURL: 'https://travel-journal-app-377b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-journal-app-377b6.firebasestorage.app',
    measurementId: 'G-GVWYJKLZ3V',
  );

}